#!/bin/bash
# Increment ESP32 firmware build number and regenerate Version.h.
# Run before each `arduino-cli compile` (or integrate into deploy.sh).

set -e

DIR="$(cd "$(dirname "$0")/.." && pwd)"
FILE="$DIR/build_number.txt"

if [ ! -f "$FILE" ]; then
    echo "0" > "$FILE"
fi

N=$(($(cat "$FILE") + 1))
echo "$N" > "$FILE"

cat > "$DIR/Version.h" << EOF
#pragma once
// Auto-generated by scripts/bump_build.sh — do NOT edit manually.
// This file is gitignored.
#define FW_BUILD_NUMBER $N
EOF

echo "[ESP32] Build #$N"
